spring.application.name=TravelHub
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/travelhub
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=YourJWTSecretKeyHere
jwt.access-expiration-ms=900000       # 15 min
jwt.refresh-expiration-ms=604800000  # 7 days

# SMTP (for email verification)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=your-email-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Rate Limiting (example values)
rate.limit.requests=5
rate.limit.duration.seconds=60
